### ISSUE TITLE
Error installing V0.2

### ISSUE THREAD

**Issue by manuvinakurike** [uber-research/plato-research-dialogue-system#10]
Hi, 

I cloned the version 0.2 and got the following error message. I am using conda. All the requirements were installed without any issues. The installation worked well with V 0.1, but facing issues with 0.2. Any help will be appreciated. Thanks! 

    ERROR: Command errored out with exit status 1:
     command: anaconda3/envs/plato_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/wsvscode/plato/plato-research-dialogue-system/setup.py'"'"'; __file__='"'"'/wsvscode/plato/plato-research-dialogue-system/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /wsvscode/plato/plato-research-dialogue-system/
    Complete output (12 lines):
    mkdir: cannot create directory ‘applications’: File exists
    mkdir: cannot create directory ‘data’: File exists
    mkdir: cannot create directory ‘logs’: File exists
    mkdir: cannot create directory ‘models’: File exists
    running egg_info
    writing plato.egg-info/PKG-INFO
    writing dependency_links to plato.egg-info/dependency_links.txt
    writing entry points to plato.egg-info/entry_points.txt
    writing requirements to plato.egg-info/requires.txt
    writing top-level names to plato.egg-info/top_level.txt
    file run_plato_rds.py (for module run_plato_rds) not found
    error: package directory 'plato/docs/images' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by chagri** [comment]
It is not recommended to install source distributions directly using conda.  Please look at the following  discussion: https://stackoverflow.com/questions/40756482/can-conda-install-source-distributions

If you have conda installed, then your "pip" should default to conda "pip" (unless pip is explicitly set to another python). We would recommend the following:

1. uninstall plato v0.1 using pip
2. install Plato v0.2 using pip from from the source using: ```"pip install -e . " or "python setup.py install"```

This should use conda-pip to install Palto v0.2

**Comment by manuvinakurike** [comment]
Thanks! That worked!

**Comment by chagri** [comment]
Awesome!
