### ISSUE TITLE
why need DM and NLG when train NLU?

### ISSUE THREAD

**Issue by guhuawuli** [uber-research/plato-research-dialogue-system#12]
In tutorial (https://github.com/uber-research/plato-research-dialogue-system) I fond one part which is " Train NLU"

Since it is trained by 

ludwig experiment \
       --model_definition_file plato/example/config/ludwig/ludwig_nlu_train.yaml \
       --data_csv data/DSTC2_NLU_sys.csv \
       --output_directory models/camrest_nlu/sys/
why we still need:
plato run --config CamRest_model_nlu.yaml

From CamRest_model_nlu.yaml I can see part DM and part NLG. Since it just need to train nlu what's the purpose of the other two part?
![屏幕快照 2019-11-21 下午8 43 47](https://user-images.githubusercontent.com/23067203/69339278-ee907780-0c9f-11ea-960b-c449fd39561f.png)

**Comment by apapangelis** [comment]
Hi, the purpose of the second part is to actually run a conversational agent that will load and use the trained NLU (that was trained with ludwig in the previous step). So, this agent still needs a DM and NLG to operate but if you see the NLU section it loads the trained model.

I hope this helps!
