### ISSUE TITLE
ValueError: Configuration file CamRest_text.yaml not found!

### ISSUE THREAD

**Issue by yan624** [uber-research/plato-research-dialogue-system#14]
My computer is windows. I ran this command: `plato run --config CamRest_text.yaml`

I don't know if I installed it wrong, but I have an error which is `ValueError: Configuration file CamRest_text.yaml not found!`.

I had found the reason in `/plato/controller/basic_controller.py`, line 415. You use `'/'` to split plato path in windows. I use `os.sep` instead of `'/'`, which did work.

**Comment by BrianInGermany** [comment]
I also have an issue with file paths not being found in Windows.
I will try with linux.

**Comment by BrianInGermany** [comment]
Works on my linux machine.
