### ISSUE TITLE
Integrate model with new dataset 

### ISSUE THREAD

**Issue by HarshitaSahai** [uber-research/plato-research-dialogue-system#15]
I would like to use the model for my dataset. Completed the following steps: 

1. Created domain ( ontology and database)
2. "plato run --config <FULL PATH TO CONFIG YAML FILE>" successful run
3. Extracted DSTC2 and changed the ontology mentioned inside it as per my data.

After this, I'm unable to understand how to move forward. Could you please guide me?

Thank you

**Comment by al3xpapangelis** [comment]
Are you using DSTC2 data or another dataset? (The DSTC2 parsers are specific to DSTC2 data)

**Comment by HarshitaSahai** [comment]
I'm using DSTC2 but in the section where ontology is specified, I had updated my ontology. Will it work then or internally also it is associated with CamRest.
Also while doing the slotting manually I'm facing issue like how I can run that and check it. If you could guide me with that?

Thanks

**Comment by al3xpapangelis** [comment]
Well, if you train models on DSTC and then use a different ontology it won't work. But if you use a new ontology (and database), then it should work but you need to either parse your own data that correspond to that ontology or create simulated data using Plato's simulators.

If you want to train models (using your own or simulated data), then I would suggest to start by writing a parser (look at the DSTC2 or MetalWOZ parsers). Then you can modify the Ludwig configs to represent your dataset attributes and write interfaces similar to camrest_nlu, etc.

I hope this helps!
