### ISSUE TITLE
Problems downloading DSTC2

### ISSUE THREAD

**Issue by hsm207** [uber-research/plato-research-dialogue-system#19]
The README is using DSTC2 as the example. However, the link  to download the file at http://camdial.org/~mh521/dstc/downloads/dstc2_traindev.tar.gz
 appears to be dead so we can't follow the rest of the tutorial. 

Is there an alternative link to download DSTC2 or can be examples be updated to use MetaLWOz instead?

**Comment by al3xpapangelis** [comment]
Here's the new link:

https://github.com/matthen/dstc

We'll update the README soon.
