### ISSUE TITLE
How to Train with Deep Learning Framework?

### ISSUE THREAD

**Issue by ayaz-amin** [uber-research/plato-research-dialogue-system#3]
I read the docs and noticed that models are currently trainable using Ludwig (although it mentioned that models can be trained in Tensorflow or PyTorch as well). I want to be able to train models using a DL framework. Is it doable right now?

**Comment by chagri** [comment]
Plato is compatible with any Python Library. You can extend Plato with any
library of your choice: TF, PyTorch, Keras, etc. by writing custom code.

**Comment by ayaz-amin** [comment]
Thanks for replying! I will try to use Plato with Keras, and if successful, create an extension for Plato.

**Comment by kouohhashi** [comment]
@ayaz-amin 
Hi, have you use Tensorflow or Pytorch with Plato?
If so could you share tips here or blog?

I think tutorial with TF or Pytorch is convenient for many developers because most developers use TF or Pytorch. Ludwig is not for developers...

**Comment by w4nderlust** [comment]
@kouohhashi  I suggest you to take a closer look at Ludwig. It covers all dialogue systems component modeling use cases, and if you can be extremely easily extend it for any use case you have in mind as it provides a tensor-in tensor-out interface inside which you can put whatever model you want, even though the most common ones are already available to you as they have already been implemented.
