### ISSUE TITLE
Why not an MIT, Apache, or other common license?

### ISSUE THREAD

**Issue by arschles** [uber-research/plato-research-dialogue-system#4]
The license for this project is not familiar to me. I fully respect the choice to use whatever license you choose, but I was wondering if there's a reason this repository (and others in the uber-research GH organization) don't use one of the more common OSS licenses?

**Comment by bhenhsi** [comment]
Hi @arschles, Plato source code is shared under a non-commercial license for research purposes only. Most of the research projects under uber-research are under the same non-commercial license. We constantly assess projects under uber-research and relicense them under open source license whenever possible. E.g. we recently relicensed POET under Apache 2.0 https://github.com/uber-research/poet 

Let me know if you have future questions.

**Comment by arschles** [comment]
Thanks for the explanation @briankhsieh. Do you initially release as non-commercial because you have non-commercial licensed dependencies, or unvetted licensed software that you depend on?
