### ISSUE TITLE
Bug in argunment handling

### ISSUE THREAD

**Issue by petasis** [uber-research/plato-research-dialogue-system#5]
Hi all,

I am getting an error while trying to reproduce the examples, like:

python3 runPlatoRDS.py -config Examples/config/simulate_text.yaml

Traceback (most recent call last):
  File "runPlatoRDS.py", line 416, in <module>
    if arguments['test_mode']:
KeyError: 'test_mode'

Maybe using arguments.get(), instead of arguments[]?

**Comment by apapangelis** [comment]
Thanks! Could you try again?

**Comment by petasis** [comment]
Thanks, the latest updated fixed the issue.
