### ISSUE TITLE
Make some proper tutorials for Plato

### ISSUE THREAD

**Issue by peterclemenko** [uber-research/plato-research-dialogue-system#6]
I love the idea of plato, but have no idea how to use it. A proper set of tutorials would be really useful.

**Comment by apapangelis** [comment]
Can you check the current tutorials? What level of detail are you looking for?

**Comment by ccuiyuhan** [comment]
when I run plato gui --config CamRest_GUI_speech.yaml 
I got an NameError: name 'open' is not defined” 
How to solve it? thank you!
