### ISSUE TITLE
Change to Permissive License 

### ISSUE THREAD

**Issue by JRMeyer** [uber-research/plato-research-dialogue-system#7]
Currently you have a custom, non-commercial license. Even though this is a research toolkit, you will have much fewer teams interested in using `Plato` without a more permissive license.

Maybe you should used the same [Apache License used in Ludwig](https://github.com/uber/ludwig/blob/master/LICENSE)?

**Comment by papadako** [comment]
I guess this has been resolved, based on the latest commits.
