### ISSUE TITLE
example for flower shop has issue

### ISSUE THREAD

**Issue by cometta** [uber-research/plato-research-dialogue-system#8]
> SYSTEM > Which price do you prefer?
> USER > the price is around $2
> SYSTEM > Which price do you prefer?
> USER > I prefer to buy it at $2 dollar
> SYSTEM > Which price do you prefer?
> USER > two dollar
> SYSTEM > Which price do you prefer?
> USER > 2 dollar
> SYSTEM > Which price do you prefer?
> USER > $2 dollar
> SYSTEM > Which price do you prefer?
> USER > 2
> SYSTEM > Which price do you prefer?
> USER > moderately priced
> SYSTEM > Which price do you prefer?
> USER > moderate
> SYSTEM > Which price do you prefer?
> USER >

why the system keep asking the same question?

**Comment by apapangelis** [comment]
Hi, it seems that the values are converted to floating points, so if you would say something like '2.0' instead of '2' it should work. I'll revise the example, thanks!

**Comment by apapangelis** [comment]
Hi, we'e made some updates on the new version, I've checked that this works - let me know if it still breaks.
